/**
 * ROOT LAYOUT COMPONENT
 * 
 * This is the root layout component for the Next.js application.
 * It wraps all pages and provides global configuration including
 * fonts, metadata, and HTML structure.
 * 
 * The layout uses the Geist font family for a modern, clean appearance
 * and applies global CSS styles to all pages.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Geist Sans Font Configuration
 * 
 * Configures the primary sans-serif font for the application.
 * The Geist font family provides excellent readability and a modern appearance.
 * The variable is used to apply the font via CSS custom properties.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Geist Mono Font Configuration
 * 
 * Configures the monospace font for code and technical content.
 * This font is used for displaying room codes and other technical information
 * where a monospace font improves readability.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Application Metadata
 * 
 * Defines the metadata for the application that appears in browser tabs,
 * search results, and social media previews. This should be updated
 * with proper game-specific information in production.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout Component
 * 
 * The root layout component that wraps all pages in the application.
 * It provides the basic HTML structure and applies global font configurations.
 * 
 * @param children - React nodes representing the page content
 * @returns JSX element containing the complete HTML structure
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
